kind: pipeline
name: build-discordbot_docker-image

steps:
  - name: build
    image: docker:latest
    commands:
      - docker build -t discordbot -f Dockerfile.prod .

  - name: publish
    image: plugins/docker
    settings:
      registry: trompot.sakuracr.jp
      repo: discordbot
      tags: latest
      username:
        from_secret: secrets.DOCKER_USERNAME
      password:
        from_secret: secrets.DOCKER_PASSWORD
