name: Docker Build

on:
  push:
    branches:
      - master

jobs:
  push_to_registry:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Prepare Build Arg
        id: prepare_build_arg
        run: |
          CURRENT_TAG=${GITHUB_REF#refs/tags/}
          echo ::set-output name=CURRENT_TAG::${CURRENT_TAG}
          echo ::set-output name=RUBY_VERSION::${CURRENT_TAG%-*}
          echo ::set-output name=BUNDLER_VERSION::${CURRENT_TAG##*-}

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/discordbot:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/discordbot:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/discordbot:buildcache,mode=max
